/// Comprehensive Multilingual dictionary supporting 10 languages with exact RTL/LTR support.
class AppStrings {
  static bool isRtl(String lang) {
    return lang == 'fa' || lang == 'ar' || lang == 'ckb';
  }

  static String getArrow(String lang) {
    return isRtl(lang) ? '←' : '→';
  }

  static final Map<String, Map<String, String>> _translations = {
    // 1. FARSI / PERSIAN (فارسی - RTL)
    'fa': {
      'my_alerts': 'هشدارهای من',
      'history': 'تاریخچه',
      'settings': 'تنظیمات',
      'smart_alerts_desc': 'بررسی هوشمند بر اساس زمان‌بندی دلخواه',
      'new_alert': 'افزودن هشدار جدید',
      'last_checked_price': 'آخرین قیمت بررسی‌شده:',
      'check_now': 'بررسی آنی',
      'baseline': 'مبنا',
      'rearm': 'فعال‌سازی مجدد',
      'theme_and_colors': 'پوسته و رنگ‌بندی',
      'theme_dark_green': 'زمردی تاریک (پیش‌فرض)',
      'theme_light_green': 'زمردی روشن',
      'theme_dark_orange': 'نارنجی تاریک',
      'theme_light_orange': 'نارنجی روشن',
      'select_language': 'زبان برنامه',
      'sound_and_vibrate': 'صدا و لرزش (Sound & Haptics)',
      'sound_alert': 'صدای هشدار و آلارم',
      'vibrate_alert': 'ویبره هنگام هشدار',
      'test_sound_button': '🔔 تست صدای آلارم و نوتیفیکیشن',
      'backup_and_restore': 'پشتیبان‌گیری و بازیابی',
      'export_backup': 'پشتیبان‌گیری از هشدارها (Export)',
      'restore_backup': 'بازیابی هشدارها (Restore)',
      'clear_history': 'پاک‌سازی تاریخچه اعلان‌ها',
      'battery_settings': 'بهینه‌سازی باتری در پس‌زمینه (Android)',
      'battery_active': 'معاف از بهینه‌سازی باتری (اجرای مطمئن)',
      'battery_request': 'درخواست معافیت باتری',
      'test_alert_title': 'تست سامانه هشدار Alarmer',
      'test_alert_body': 'صدا و اعلان تستی با موفقیت روی دستگاه شما به صدا درآمد!',
      'backup_copied': '✅ پشتیبان‌گیری انجام شد و در کلیپ‌بورد کپی گردید.',
      'restore_success': 'هشدارها با موفقیت بازیابی شدند.',
      'exchange': 'صرافی',
      'pair': 'جفت‌ارز',
      'create_alert_title': 'ایجاد هشدار هوشمند',
      'frequency': 'دوره بررسی',
      'seconds': 'ثانیه',
      'minutes': 'دقیقه',
      'hours': 'ساعت',
      'empty_alerts_title': 'هنوز هشداری تنظیم نشده است',
      'empty_alerts_desc': 'می‌توانید برای هر رمزارز، اوراق قرضه آمریکا یا سهام جهانی هشدار تنظیم کنید.',
      'create_first_alert': 'ایجاد اولین هشدار هوشمند',
      'choose_market_step': 'گام نخست: انتخاب نوع بازار',
      'choose_market_title': 'مایلید برای کدام بازار هشدار تنظیم کنید؟',
      'choose_market_desc': 'نوع بازار و دارایی مورد نظر خود را برای پایش دقیق قیمت انتخاب نمایید.',
      'crypto_market_title': '⚡ بازار رمزارزها (کریپتو)',
      'crypto_market_badge': 'بیش از ۴۰ صرافی معتبر',
      'crypto_market_desc': 'بیش از ۴۰ صرافی معتبر بین‌المللی و ایرانی با چیپ‌های فیلتر، استخراج جفت‌ارزها و دکمه بروزرسانی',
      'crypto_market_cta': 'ورود به بخش صرافی‌های کریپتو ←',
      'macro_market_title': '🏛️ سهام، اوراق قرضه آمریکا و فارکس',
      'macro_market_badge': 'وال استریت و اقتصاد کلان',
      'macro_market_desc': 'اوراق قرضه ۱۰ ساله آمریکا (US10Y)، جفت‌ارزهای فارکس، سهام‌های نزدک/نیویورک، طلا و شاخص‌ها',
      'macro_market_cta': 'ورود به بازارهای جهانی ←',
      'search_exchange_hint': 'جستجوی صرافی (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'جستجوی رمزارز (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'جستجوی نماد (US10Y, EUR/USD, NVDA, طلا)...',
      'refresh_list': 'بروزرسانی لیست',
      'select_cta': 'انتخاب ←',
      'selected_asset': 'دارایی انتخاب‌شده:',
      'auto_check_schedule': '۱. زمان‌بندی بررسی خودکار:',
      'unit_count': 'تعداد واحد',
      'time_unit': 'واحد زمان',
      'condition_type': '۲. نوع شرط هشدار:',
      'percent_change': 'درصد تغییر (%)',
      'price_target': 'قیمت هدف (\$)',
      'price_direction': 'جهت نوسان قیمت:',
      'both_ways': '± هر دو طرف',
      'above_only': '▲ فقط افزایش',
      'below_only': '▼ فقط کاهش',
      'target_price_label': 'قیمت هدف (دلار)',
      'percent_label': 'درصد نوسان مد نظر (%)',
      'save_alert_cta': 'ذخیره و شروع بررسی هشدار',
      'just_now': 'همین الان',
      'seconds_ago': 'ثانیه قبل',
      'minutes_ago': 'دقیقه قبل',
      'hours_ago': 'ساعت قبل',
      'days_ago': 'روز قبل',
      'every': 'هر',
      'cancel': 'انصراف',
      'confirm': 'تأیید',
      'restore_dialog_hint': 'متن فایل JSON پشتیبان‌گیری شده را در کادر زیر جای‌گذاری (Paste) کنید:',
      'restore_dialog_btn': 'تأیید و بازیابی',
      'clear_history_confirm': 'آیا از پاک کردن تمامی اعلان‌ها و رکوردهای ثبت‌شده اطمینان دارید؟',
      'clear_history_btn': 'پاک‌سازی',
      'clear_history_success': 'تمامی لاگ‌های تاریخچه اعلان‌ها پاک شدند.',
      'battery_exempt_active': 'فعال (هشدارها سر وقت اجرا می‌شوند)',
      'battery_exempt_inactive': 'غیرفعال (ممکن است سیستم هشدار را متوقف کند)',
      'battery_exempt_title': 'معافیت از محدودیت باتری',
      'battery_exempt_success': 'معافیت از بهینه‌سازی باتری با موفقیت ثبت شد.',
      'export_backup_desc': 'خروجی گرفتن از تمام هشدارهای فعال در قالب فایل JSON',
      'restore_backup_desc': 'وارد کردن و بازگردانی هشدارها از فایل یا متن JSON',
      'clear_history_desc': 'حذف تمامی گزارش‌ها و لاگ‌های ثبت‌شده',
      'filter_all': 'همه اعلان‌ها',
      'filter_triggered': 'فعال‌شده‌ها',
      'filter_suppressed': 'محدودشده‌ها',
      'no_history_title': 'تاریخچه‌ای ثبت نشده است',
      'no_history_desc': 'هنگامی که هشدارهای قیمتی شما اجرا شوند، گزارش وقایع در اینجا نمایش داده می‌شود.',
      'check_price_done': 'بررسی قیمت انجام شد: ',
      'alert_deleted_msg': 'هشدار حذف شد: ',
      'undo_action': 'بازگردانی',
      'target_price_required': 'لطفاً قیمت هدف را وارد کنید',
      'all_symbols': 'همه نمادها',
      'us_bonds': '🏛️ اوراق قرضه آمریکا',
      'forex_pairs': '💱 فارکس (ارزها)',
      'gold_metals': '🥇 طلا و فلزات',
      'wallstreet_stocks': '📈 سهام وال‌استریت',
      'global_indices': '🌐 شاخص‌های جهانی',
      'price_cross_above': 'عبور به بالاتر از (▲)',
      'price_cross_below': 'سقوط به پایین‌تر از (▼)',
      'price_cross_direction': 'جهت عبور قیمت:',
      'above_target': '▲ بالاتر از هدف',
      'below_target': '▼ پایین‌تر از هدف',
      'price_fluctuation': 'نوسان قیمت:',
      'price_surge': 'افزایش قیمت:',
      'price_drop': 'کاهش قیمت:',
      'target_price_summary': 'قیمت هدف:',
      'price_delta_summary': 'تغییر دلاری:',
      'volume_surge_summary': 'جهش حجم معاملات:',
      'interval_prefix': '⏱️ بررسی قیمت هر ',
      'interval_suffix': ' یک‌بار در پس‌زمینه انجام خواهد شد.',
      'offline_error': 'عدم دسترسی به اینترنت. آخرین قیمت واقعی نگه‌داری می‌شود.',
      'offline_badge': 'آفلاین (قیمت قبلی)',
      'edit_alert_title': 'ویرایش تنظیمات هشدار',
      'save_changes_cta': 'ذخیره تغییرات هشدار',
    },

    // 2. ENGLISH (English - LTR)
    'en': {
      'my_alerts': 'My Alerts',
      'history': 'History',
      'settings': 'Settings',
      'smart_alerts_desc': 'Intelligent monitoring based on custom schedule',
      'new_alert': 'Add New Alert',
      'last_checked_price': 'Last Checked Price:',
      'check_now': 'Check Now',
      'baseline': 'Base',
      'rearm': 'Re-arm Alert',
      'theme_and_colors': 'Theme & Color Scheme',
      'theme_dark_green': 'Dark Emerald (Default)',
      'theme_light_green': 'Light Emerald',
      'theme_dark_orange': 'Dark Orange',
      'theme_light_orange': 'Light Orange',
      'select_language': 'Language',
      'sound_and_vibrate': 'Sound & Haptics',
      'sound_alert': 'Alarm Sound',
      'vibrate_alert': 'Vibration Alert',
      'test_sound_button': '🔔 Test Alarm & Notification',
      'backup_and_restore': 'Backup & Restore',
      'export_backup': 'Export Alerts Backup (JSON)',
      'restore_backup': 'Restore Alerts (JSON)',
      'clear_history': 'Clear Notification History',
      'battery_settings': 'Battery Optimization (Android)',
      'battery_active': 'Exempt from battery optimization (Reliable)',
      'battery_request': 'Request Exemption',
      'test_alert_title': 'Alarmer Test Notification',
      'test_alert_body': 'Sound and notification successfully triggered on your device!',
      'backup_copied': '✅ Backup copied to clipboard successfully.',
      'restore_success': 'Alerts restored successfully.',
      'exchange': 'Exchange',
      'pair': 'Market Pair',
      'create_alert_title': 'Create Smart Alert',
      'frequency': 'Frequency',
      'seconds': 'Sec',
      'minutes': 'Min',
      'hours': 'Hours',
      'empty_alerts_title': 'No Alerts Configured Yet',
      'empty_alerts_desc': 'You can set percent change or price target alerts for any crypto, US bond, or global stock.',
      'create_first_alert': 'Create First Smart Alert',
      'choose_market_step': 'Step 1: Choose Market Type',
      'choose_market_title': 'Which market would you like to track?',
      'choose_market_desc': 'Select your desired market type and asset to accurately monitor prices.',
      'crypto_market_title': '⚡ Crypto Market (Cryptocurrencies)',
      'crypto_market_badge': '40+ Verified Exchanges',
      'crypto_market_desc': 'Over 40 top international and verified exchanges with category filters and pair auto-discovery.',
      'crypto_market_cta': 'Enter Crypto Exchanges →',
      'macro_market_title': '🏛️ US Stocks, Treasury Bonds & Forex',
      'macro_market_badge': 'Wall Street & Macro Economy',
      'macro_market_desc': 'US 10-Year Yields (US10Y), Forex pairs, Nasdaq/NYSE equities, Gold & Global Indices.',
      'macro_market_cta': 'Enter Global Markets →',
      'search_exchange_hint': 'Search exchange (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'Search crypto (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'Search symbol (US10Y, EUR/USD, NVDA, Gold)...',
      'refresh_list': 'Refresh Pairs',
      'select_cta': 'Select →',
      'selected_asset': 'Selected Asset:',
      'auto_check_schedule': '1. Automated Check Schedule:',
      'unit_count': 'Interval Value',
      'time_unit': 'Time Unit',
      'condition_type': '2. Alert Condition Type:',
      'percent_change': 'Percent Change (%)',
      'price_target': 'Price Target (\$)',
      'price_direction': 'Price Direction:',
      'both_ways': '± Both Ways',
      'above_only': '▲ Above Only',
      'below_only': '▼ Below Only',
      'target_price_label': 'Target Price (\$)',
      'percent_label': 'Target Percentage (%)',
      'save_alert_cta': 'Save and Start Monitoring',
      'just_now': 'Just now',
      'seconds_ago': 's ago',
      'minutes_ago': 'm ago',
      'hours_ago': 'h ago',
      'days_ago': 'd ago',
      'every': 'Every',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'restore_dialog_hint': 'Paste your exported JSON backup text into the box below:',
      'restore_dialog_btn': 'Confirm & Restore',
      'clear_history_confirm': 'Are you sure you want to clear all notification history logs?',
      'clear_history_btn': 'Clear All',
      'clear_history_success': 'All notification history logs have been cleared.',
      'battery_exempt_active': 'Active (Alerts run precisely on schedule)',
      'battery_exempt_inactive': 'Inactive (Background tasks may be paused by OS)',
      'battery_exempt_title': 'Battery Optimization Exemption',
      'battery_exempt_success': 'Battery exemption granted successfully.',
      'export_backup_desc': 'Export all active alerts to a JSON file or clipboard',
      'restore_backup_desc': 'Import and restore alerts from a JSON file or text',
      'clear_history_desc': 'Delete all stored logs and notification history',
      'filter_all': 'All Logs',
      'filter_triggered': 'Triggered',
      'filter_suppressed': 'Suppressed',
      'no_history_title': 'No History Logged Yet',
      'no_history_desc': 'When your price alert conditions are met, events will be recorded here.',
      'check_price_done': 'Price check completed: ',
      'alert_deleted_msg': 'Alert deleted: ',
      'undo_action': 'Undo',
      'target_price_required': 'Please enter a target price',
      'all_symbols': 'All Assets',
      'us_bonds': '🏛️ US Treasury Bonds',
      'forex_pairs': '💱 Forex Pairs',
      'gold_metals': '🥇 Gold & Metals',
      'wallstreet_stocks': '📈 Wall Street Equities',
      'global_indices': '🌐 Global Indices',
      'price_cross_above': 'Cross above (▲)',
      'price_cross_below': 'Drop below (▼)',
      'price_cross_direction': 'Crossing Direction:',
      'above_target': '▲ Above Target',
      'below_target': '▼ Below Target',
      'price_fluctuation': 'Price change:',
      'price_surge': 'Price increase:',
      'price_drop': 'Price drop:',
      'target_price_summary': 'Target price:',
      'price_delta_summary': 'Price delta:',
      'volume_surge_summary': 'Volume surge:',
      'interval_prefix': '⏱️ Automated price check runs every ',
      'interval_suffix': ' in background.',
      'offline_error': 'No internet connection. Keeping last recorded authentic price.',
      'offline_badge': 'Offline (Last Price)',
      'edit_alert_title': 'Edit Price Alert',
      'save_changes_cta': 'Save Alert Changes',
    },

    // 3. KURDISH SORANI (کوردی سۆرانی - RTL)
    'ckb': {
      'my_alerts': 'ئاگادارییەکانی من',
      'history': 'مێژوو',
      'settings': 'ڕێکخستنەکان',
      'smart_alerts_desc': 'چاودێری زیرەک بەپێی کاتی دیاریکراو',
      'new_alert': 'زیادکردنی ئاگاداری',
      'last_checked_price': 'دواین نرخی پشکنراو:',
      'check_now': 'پشکنینی خێرا',
      'baseline': 'بنەما',
      'rearm': 'چالاککردنەوە',
      'theme_and_colors': 'ڕووکار و ڕەنگ',
      'theme_dark_green': 'سەوزی تاریک (بنەڕەت)',
      'theme_light_green': 'سەوزی ڕووناک',
      'theme_dark_orange': 'پڕتەقاڵی تاریک',
      'theme_light_orange': 'پڕتەقاڵی ڕووناک',
      'select_language': 'زمانی بەرنامە',
      'sound_and_vibrate': 'دەنگ و لەرزین',
      'sound_alert': 'دەنگی ئاگادارکردنەوە',
      'vibrate_alert': 'لەرزین لە کاتی ئاگاداری',
      'test_sound_button': '🔔 تاقیکردنەوەی دەنگ و ئاگاداری',
      'backup_and_restore': 'هەڵگرتنەوە و گێڕانەوە',
      'export_backup': 'هەڵگرتنی پاڵپشت (Export JSON)',
      'restore_backup': 'گێڕانەوەی ئاگادارییەکان (Restore)',
      'clear_history': 'سڕینەوەی مێژووی ئاگادارییەکان',
      'battery_settings': 'ڕێکخستنی پاتری (Android)',
      'battery_active': 'بەخشراو لە سنوورداری پاتری',
      'battery_request': 'داواکردنی بەخشین',
      'test_alert_title': 'تاقیکردنەوەی ئاگاداری',
      'test_alert_body': 'دەنگ و ئاگاداری بە سەرکەوتوویی تاقیکرایەوە!',
      'backup_copied': '✅ پاڵپشت لە کلیپبۆرد کۆپیکرا.',
      'restore_success': 'ئاگادارییەکان گەڕێنرانەوە.',
      'exchange': 'بۆرسە',
      'pair': 'جووتە دراو',
      'create_alert_title': 'دروستکردنی ئاگاداری نوێ',
      'frequency': 'ماوەی پشکنین',
      'seconds': 'چرکە',
      'minutes': 'خولەک',
      'hours': 'کاتژمێر',
      'empty_alerts_title': 'هیچ ئاگادارییەک دانەنراوە',
      'empty_alerts_desc': 'دەتوانیت بۆ کریپتۆ، بۆندەکانی ئەمریکا یان پشکەکان ئاگاداری دابنێیت.',
      'create_first_alert': 'یەکەم ئاگاداری دروست بکە',
      'choose_market_step': 'هەنگاوی یەکەم: هەڵبژاردنی بازاڕ',
      'choose_market_title': 'دەتەوێت بۆ کام بازاڕ ئاگاداری دابنێیت؟',
      'choose_market_desc': 'جۆری بازاڕ و سەرمایەی مەبەست هەڵبژێرە.',
      'crypto_market_title': '⚡ بازاڕی دراوی کریپتۆ',
      'crypto_market_badge': 'زیاتر لە ٤٠ بۆرسەی باوەڕپێکراو',
      'crypto_market_desc': 'زیاتر لە ٤٠ بۆرسەی نێودەوڵەتی بە فلتەری جۆراوجۆر و جفتە دراوەکانەوە.',
      'crypto_market_cta': 'چوونە ناو بۆرسەکانی کریپتۆ ←',
      'macro_market_title': '🏛️ پشکەکان، بۆندەکانی ئەمریکا و فۆرێکس',
      'macro_market_badge': 'واڵ ستریت و ئابووری جیهانی',
      'macro_market_desc': 'بۆندی ۱۰ ساڵەی ئەمریکا، فۆرێکس، پشکەکانی نەزداک و زێڕ.',
      'macro_market_cta': 'چوونە ناو بازاڕە جیهانییەکان ←',
      'search_exchange_hint': 'گەڕان بۆ بۆرسە (Binance, Nobitex, Wallex)...',
      'search_crypto_hint': 'گەڕان بۆ کریپتۆ (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'گەڕان بۆ هێما (US10Y, EUR/USD, زێڕ)...',
      'refresh_list': 'نوێکردنەوەی لیست',
      'select_cta': 'هەڵبژاردن ←',
      'selected_asset': 'سەرمایەی هەڵبژێردراو:',
      'auto_check_schedule': '١. کاتی پشکنینی خۆکار:',
      'unit_count': 'ژمارە',
      'time_unit': 'یەکەی کات',
      'condition_type': '٢. مەرجی ئاگاداری:',
      'percent_change': 'ڕێژەی گۆڕان (%)',
      'price_target': 'نرخی مەبەست (\$)',
      'price_direction': 'ئاراستەی نرخ:',
      'both_ways': '± هەردوو لا',
      'above_only': '▲ تەنها بەرزبوونەوە',
      'below_only': '▼ تەنها دابەزین',
      'target_price_label': 'نرخی مەبەست (دۆلار)',
      'percent_label': 'ڕێژەی سەدی (%)',
      'save_alert_cta': 'پاشەکەوت و دەستپێکردنی چاودێری',
      'just_now': 'ئێستا',
      'seconds_ago': 'چرکە لەمەوبەر',
      'minutes_ago': 'خولەک لەمەوبەر',
      'hours_ago': 'کاتژمێر لەمەوبەر',
      'days_ago': 'ڕۆژ لەمەوبەر',
      'every': 'هەموو',
      'cancel': 'پاشگەزبوونەوە',
      'confirm': 'پەسەندکردن',
      'restore_dialog_hint': 'دەقی فایلی JSON لەم خانەیەدا دابنێ:',
      'restore_dialog_btn': 'پەسەند و گێڕانەوە',
      'clear_history_confirm': 'ئایا دڵنیایت لە سڕینەوەی هەموو مێژووەکە؟',
      'clear_history_btn': 'سڕینەوە',
      'clear_history_success': 'هەموو مێژووەکە سڕایەوە.',
      'battery_exempt_active': 'چالاکە',
      'battery_exempt_inactive': 'ناچالاکە',
      'battery_exempt_title': 'بەخشینی پاتری',
      'battery_exempt_success': 'بەخشینی پاتری بە سەرکەوتوویی ئەنجامدرا.',
      'export_backup_desc': 'دەرهێنانی هەموو ئاگادارییەکان وەک فایلی JSON',
      'restore_backup_desc': 'گێڕانەوەی ئاگادارییەکان لە فایلی JSON',
      'clear_history_desc': 'سڕینەوەی هەموو مێژوو و ئاگادارییە تۆمارکراوەکان',
      'filter_all': 'هەمووی',
      'filter_triggered': 'لێدراوەکان',
      'filter_suppressed': 'ڕاگیراوەکان',
      'no_history_title': 'هیچ مێژوویەک نییە',
      'no_history_desc': 'کاتێک ئاگادارییەکان کار دەکەن، ڕاپۆرتەکان لێرە دەردەکەون.',
      'check_price_done': 'پشکنینی نرخ ئەنجامدرا: ',
      'alert_deleted_msg': 'ئاگاداری سڕایەوە: ',
      'undo_action': 'گێڕانەوە',
      'target_price_required': 'تکایە نرخی مەبەست بنووسە',
      'all_symbols': 'هەموو نمادەکان',
      'us_bonds': '🏛️ بۆندەکانی ئەمریکا',
      'forex_pairs': '💱 فۆرێکس',
      'gold_metals': '🥇 زێڕ و کانزاکان',
      'wallstreet_stocks': '📈 پشکەکانی واڵ ستریت',
      'global_indices': '🌐 پێوەرە جیهانییەکان',
      'price_cross_above': 'تێپەڕین بۆ سەرەوە (▲)',
      'price_cross_below': 'دابەزین بۆ خوارەوە (▼)',
      'price_cross_direction': 'ئاراستەی تێپەڕین:',
      'above_target': '▲ سەرووی مەبەست',
      'below_target': '▼ خوارووی مەبەست',
      'price_fluctuation': 'گۆڕانی نرخ:',
      'price_surge': 'بەرزبوونەوەی نرخ:',
      'price_drop': 'دابەزینی نرخ:',
      'target_price_summary': 'نرخی مەبەست:',
      'price_delta_summary': 'گۆڕانی دۆلاری:',
      'volume_surge_summary': 'بەرزبوونەوەی قەبارە:',
      'interval_prefix': '⏱️ پشکنینی نرخ هەر ',
      'interval_suffix': ' جارێک لە پاشبنەما ئەنجام دەدرێت.',
    },

    // 4. ARABIC (العربية - RTL)
    'ar': {
      'my_alerts': 'تنبيهاتي',
      'history': 'السجل',
      'settings': 'الإعدادات',
      'smart_alerts_desc': 'مراقبة ذكية للأسعار حسب جدول زمني مخصص',
      'new_alert': 'إضافة تنبيه جديد',
      'last_checked_price': 'آخر سعر تم فحصه:',
      'check_now': 'فحص فوري',
      'baseline': 'الأساس',
      'rearm': 'إعادة التفعيل',
      'theme_and_colors': 'المظهر والألوان',
      'theme_dark_green': 'الزمردي الداكن (الافتراضي)',
      'theme_light_green': 'الزمردي الفاتح',
      'theme_dark_orange': 'البرتقالي الداكن',
      'theme_light_orange': 'البرتقالي الفاتح',
      'select_language': 'لغة التطبيق',
      'sound_and_vibrate': 'الصوت والاهتزاز',
      'sound_alert': 'صوت المنبه والإنذار',
      'vibrate_alert': 'الاهتزاز عند التنبيه',
      'test_sound_button': '🔔 اختبار صوت التنبيه والإشعار',
      'backup_and_restore': 'النسخ الاحتياطي والاستعادة',
      'export_backup': 'تصدير التنبيهات (JSON)',
      'restore_backup': 'استعادة التنبيهات (JSON)',
      'clear_history': 'مسح سجل الإشعارات',
      'battery_settings': 'تحسين البطارية (Android)',
      'battery_active': 'مستثنى من تحسين البطارية',
      'battery_request': 'طلب الاستثناء',
      'test_alert_title': 'إشعار اختبار المنبه',
      'test_alert_body': 'تم إطلاق صوت التنبيه والإشعار بنجاح على جهازك!',
      'backup_copied': '✅ تم نسخ النسخة الاحتياطية إلى الحافظة بنجاح.',
      'restore_success': 'تمت استعادة التنبيهات بنجاح.',
      'exchange': 'المنصة',
      'pair': 'زوج التداول',
      'create_alert_title': 'إنشاء تنبيه ذكي',
      'frequency': 'فترة الفحص',
      'seconds': 'ثانية',
      'minutes': 'دقيقة',
      'hours': 'ساعة',
      'empty_alerts_title': 'لم يتم ضبط أي تنبيهات بعد',
      'empty_alerts_desc': 'يمكنك ضبط تنبيهات لتغير النسبة المئوية أو السعر المستهدف للعملات المشفرة وسندات الخزانة والأسهم العالمية.',
      'create_first_alert': 'إنشاء أول تنبيه ذكي',
      'choose_market_step': 'الخطوة الأولى: اختيار نوع السوق',
      'choose_market_title': 'ما السوق الذي ترغب في متابعته؟',
      'choose_market_desc': 'حدد نوع السوق والأصل المطلوب لمراقبة الأسعار بدقة.',
      'crypto_market_title': '⚡ سوق العملات المشفرة (Crypto)',
      'crypto_market_badge': 'أكثر من ٤٠ منصة معتمدة',
      'crypto_market_desc': 'أكثر من ٤٠ منصة دولية ومحلية مع فلاتر التصنيف وجلب أزواج التداول وزر التحديث.',
      'crypto_market_cta': 'الدخول إلى منصات العملات المشفرة ←',
      'macro_market_title': '🏛️ الأسهم الأمريكية وسندات الخزانة والفوركس',
      'macro_market_badge': 'وول ستريت والاقتصاد الكلي',
      'macro_market_desc': 'سندات الخزانة الأمريكية (US10Y) وأزواج الفوركس وأسهم ناسداك والذهب والمؤشرات.',
      'macro_market_cta': 'الدخول إلى الأسواق العالمية ←',
      'search_exchange_hint': 'البحث عن منصة (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'البحث عن عملة (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'البحث عن رمز (US10Y, EUR/USD, NVDA, الذهب)...',
      'refresh_list': 'تحديث القائمة',
      'select_cta': 'اختيار ←',
      'selected_asset': 'الأصل المحدد:',
      'auto_check_schedule': '١. جدول الفحص التلقائي:',
      'unit_count': 'القيمة',
      'time_unit': 'وحدة الوقت',
      'condition_type': '٢. نوع شرط التنبيه:',
      'percent_change': 'نسبة التغير (%)',
      'price_target': 'السعر المستهدف (\$)',
      'price_direction': 'اتجاه حركة السعر:',
      'both_ways': '± كلا الاتجاهين',
      'above_only': '▲ ارتفاع فقط',
      'below_only': '▼ انخفاض فقط',
      'target_price_label': 'السعر المستهدف (بالدولار)',
      'percent_label': 'النسبة المئوية المطلوبة (%)',
      'save_alert_cta': 'حفظ وبدء المراقبة',
      'just_now': 'الآن',
      'seconds_ago': 'ثوانٍ مضت',
      'minutes_ago': 'دقائق مضت',
      'hours_ago': 'ساعات مضت',
      'days_ago': 'أيام مضت',
      'every': 'كل',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'restore_dialog_hint': 'الصق نص النسخة الاحتياطية JSON في المربع أدناه:',
      'restore_dialog_btn': 'تأكيد واستعادة',
      'clear_history_confirm': 'هل أنت متأكد من رغبتك في مسح كافة سجلات الإشعارات؟',
      'clear_history_btn': 'مسح الكل',
      'clear_history_success': 'تم مسح كافة سجلات الإشعارات بنجاح.',
      'battery_exempt_active': 'نشط (تعمل التنبيهات في موعدها بدقة)',
      'battery_exempt_inactive': 'غير نشط (قد يوقف النظام التنبيهات في الخلفية)',
      'battery_exempt_title': 'استثناء تحسين البطارية',
      'battery_exempt_success': 'تم منح استثناء البطارية بنجاح.',
      'export_backup_desc': 'تصدير جميع التنبيهات النشطة إلى ملف JSON',
      'restore_backup_desc': 'استيراد واستعادة التنبيهات من ملف أو نص JSON',
      'clear_history_desc': 'حذف جميع السجلات والتنبيهات السابقة',
      'filter_all': 'الكل',
      'filter_triggered': 'المنفذة',
      'filter_suppressed': 'المقيدة',
      'no_history_title': 'لا يوجد سجل بعد',
      'no_history_desc': 'عند تحقق شروط التنبيه، سيتم تسجيل الأحداث هنا.',
      'check_price_done': 'تم فحص السعر: ',
      'alert_deleted_msg': 'تم حذف التنبيه: ',
      'undo_action': 'تراجع',
      'target_price_required': 'يرجى إدخال السعر المستهدف',
      'all_symbols': 'كافة الرموز',
      'us_bonds': '🏛️ سندات الخزانة الأمريكية',
      'forex_pairs': '💱 أزواج الفوركس',
      'gold_metals': '🥇 الذهب والمعادن',
      'wallstreet_stocks': '📈 أسهم وول ستريت',
      'global_indices': '🌐 المؤشرات العالمية',
      'price_cross_above': 'تجاوز للأعلى (▲)',
      'price_cross_below': 'هبوط للأسفل (▼)',
      'price_cross_direction': 'اتجاه التجاوز:',
      'above_target': '▲ أعلى من المستهدف',
      'below_target': '▼ أدنى من المستهدف',
      'price_fluctuation': 'تغير السعر:',
      'price_surge': 'ارتفاع السعر:',
      'price_drop': 'انخفاض السعر:',
      'target_price_summary': 'السعر المستهدف:',
      'price_delta_summary': 'فارق السعر:',
      'volume_surge_summary': 'قفزة في حجم التداول:',
      'interval_prefix': '⏱️ يتم فحص السعر تلقائياً كل ',
      'interval_suffix': ' في الخلفية.',
    },

    // 5. GERMAN (Deutsch - LTR)
    'de': {
      'my_alerts': 'Meine Alarme',
      'history': 'Verlauf',
      'settings': 'Einstellungen',
      'smart_alerts_desc': 'Intelligente Überwachung nach individuellem Zeitplan',
      'new_alert': 'Neuer Alarm',
      'last_checked_price': 'Zuletzt geprüfter Preis:',
      'check_now': 'Jetzt prüfen',
      'baseline': 'Basis',
      'rearm': 'Erneut scharfstellen',
      'theme_and_colors': 'Design & Farbpalette',
      'theme_dark_green': 'Dunkel-Smaragd (Standard)',
      'theme_light_green': 'Hell-Smaragd',
      'theme_dark_orange': 'Dunkel-Orange',
      'theme_light_orange': 'Hell-Orange',
      'select_language': 'Sprache',
      'sound_and_vibrate': 'Ton & Vibration',
      'sound_alert': 'Alarmton',
      'vibrate_alert': 'Vibrationsalarm',
      'test_sound_button': '🔔 Alarm & Benachrichtigung testen',
      'backup_and_restore': 'Sicherung & Wiederherstellung',
      'export_backup': 'Alarme exportieren (JSON)',
      'restore_backup': 'Alarme wiederherstellen (JSON)',
      'clear_history': 'Benachrichtigungsverlauf löschen',
      'battery_settings': 'Akku-Optimierung (Android)',
      'battery_active': 'Von Akku-Optimierung ausgenommen',
      'battery_request': 'Ausnahme anfordern',
      'test_alert_title': 'Alarmer Testbenachrichtigung',
      'test_alert_body': 'Ton und Benachrichtigung wurden erfolgreich auf Ihrem Gerät ausgelöst!',
      'backup_copied': '✅ Sicherung erfolgreich in die Zwischenablage kopiert.',
      'restore_success': 'Alarme erfolgreich wiederhergestellt.',
      'exchange': 'Börse',
      'pair': 'Handelspaar',
      'create_alert_title': 'Smart-Alarm erstellen',
      'frequency': 'Intervall',
      'seconds': 'Sek',
      'minutes': 'Min',
      'hours': 'Std',
      'empty_alerts_title': 'Noch keine Alarme konfiguriert',
      'empty_alerts_desc': 'Erstellen Sie prozentuale oder Zielpreis-Alarme für Krypto, US-Anleihen oder Aktien.',
      'create_first_alert': 'Ersten Smart-Alarm erstellen',
      'choose_market_step': 'Schritt 1: Markt wählen',
      'choose_market_title': 'Welchen Markt möchten Sie überwachen?',
      'choose_market_desc': 'Wählen Sie den Markt und das gewünschte Asset aus.',
      'crypto_market_title': '⚡ Krypto-Markt (Kryptowährungen)',
      'crypto_market_badge': 'Über 40 verifizierte Börsen',
      'crypto_market_desc': 'Über 40 Top-Börsen mit Kategoriefiltern und Paar-Erkennung.',
      'crypto_market_cta': 'Zu den Krypto-Börsen →',
      'macro_market_title': '🏛️ US-Aktien, Anleihen & Forex',
      'macro_market_badge': 'Wall Street & Makroökonomie',
      'macro_market_desc': 'US 10-Jahres-Renditen (US10Y), Forex, Nasdaq/NYSE Aktien & Gold.',
      'macro_market_cta': 'Zu den globalen Märkten →',
      'search_exchange_hint': 'Börse suchen (Binance, Nobitex, Wallex, KuCoin)...',
      'search_crypto_hint': 'Krypto suchen (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Symbol suchen (US10Y, EUR/USD, NVDA, Gold)...',
      'refresh_list': 'Paare aktualisieren',
      'select_cta': 'Auswählen →',
      'selected_asset': 'Ausgewähltes Asset:',
      'auto_check_schedule': '1. Automatischer Prüfzeitplan:',
      'unit_count': 'Intervallwert',
      'time_unit': 'Zeiteinheit',
      'condition_type': '2. Alarmbedingung:',
      'percent_change': 'Prozentuale Änderung (%)',
      'price_target': 'Zielpreis (\$)',
      'price_direction': 'Kursrichtung:',
      'both_ways': '± Beide Richtungen',
      'above_only': '▲ Nur Anstieg',
      'below_only': '▼ Nur Rückgang',
      'target_price_label': 'Zielpreis (\$)',
      'percent_label': 'Prozentsatz (%)',
      'save_alert_cta': 'Speichern und Überwachung starten',
      'just_now': 'Gerade eben',
      'seconds_ago': 'vor s',
      'minutes_ago': 'vor m',
      'hours_ago': 'vor h',
      'days_ago': 'vor d',
      'every': 'Alle',
      'cancel': 'Abbrechen',
      'confirm': 'Bestätigen',
      'restore_dialog_hint': 'Fügen Sie den JSON-Sicherungstext in das Feld ein:',
      'restore_dialog_btn': 'Bestätigen & Wiederherstellen',
      'clear_history_confirm': 'Möchten Sie wirklich den gesamten Benachrichtigungsverlauf löschen?',
      'clear_history_btn': 'Alles löschen',
      'clear_history_success': 'Der Benachrichtigungsverlauf wurde gelöscht.',
      'battery_exempt_active': 'Aktiv (Alarme laufen pünktlich im Hintergrund)',
      'battery_exempt_inactive': 'Inaktiv (Hintergrundprüfungen können pausiert werden)',
      'battery_exempt_title': 'Akku-Optimierungs-Ausnahme',
      'battery_exempt_success': 'Ausnahme erfolgreich erteilt.',
      'export_backup_desc': 'Alle aktiven Alarme als JSON exportieren',
      'restore_backup_desc': 'Alarme aus JSON-Text importieren',
      'clear_history_desc': 'Alle gespeicherten Protokolle löschen',
      'filter_all': 'Alle',
      'filter_triggered': 'Ausgelöst',
      'filter_suppressed': 'Unterdrückt',
      'no_history_title': 'Noch kein Verlauf vorhanden',
      'no_history_desc': 'Sobald Alarmbedingungen eintreffen, werden Ereignisse hier protokolliert.',
      'check_price_done': 'Preisprüfung abgeschlossen: ',
      'alert_deleted_msg': 'Alarm gelöscht: ',
      'undo_action': 'Rückgängig',
      'target_price_required': 'Bitte geben Sie einen Zielpreis ein',
      'all_symbols': 'Alle Assets',
      'us_bonds': '🏛️ US-Staatsanleihen',
      'forex_pairs': '💱 Devisenpaare (Forex)',
      'gold_metals': '🥇 Gold & Metalle',
      'wallstreet_stocks': '📈 Wall Street Aktien',
      'global_indices': '🌐 Globale Indizes',
      'price_cross_above': 'Übersteigen nach oben (▲)',
      'price_cross_below': 'Fallen nach unten (▼)',
      'price_cross_direction': 'Durchbruchsrichtung:',
      'above_target': '▲ Über Zielpreis',
      'below_target': '▼ Unter Zielpreis',
      'price_fluctuation': 'Kursbewegung:',
      'price_surge': 'Kursanstieg:',
      'price_drop': 'Kursrückgang:',
      'target_price_summary': 'Zielpreis:',
      'price_delta_summary': 'Preis-Delta:',
      'volume_surge_summary': 'Volumensprung:',
      'interval_prefix': '⏱️ Preisprüfung läuft alle ',
      'interval_suffix': ' im Hintergrund.',
    },

    // 6. FRENCH (Français - LTR)
    'fr': {
      'my_alerts': 'Mes Alertes',
      'history': 'Historique',
      'settings': 'Paramètres',
      'smart_alerts_desc': 'Surveillance intelligente selon calendrier personnalisé',
      'new_alert': 'Nouvelle Alerte',
      'last_checked_price': 'Dernier prix vérifié :',
      'check_now': 'Vérifier maintenant',
      'baseline': 'Base',
      'rearm': 'Réarmer l’alerte',
      'theme_and_colors': 'Thème et Couleurs',
      'theme_dark_green': 'Émeraude Sombre (Défaut)',
      'theme_light_green': 'Émeraude Clair',
      'theme_dark_orange': 'Orange Sombre',
      'theme_light_orange': 'Orange Clair',
      'select_language': 'Langue',
      'sound_and_vibrate': 'Son et Vibrations',
      'sound_alert': 'Sonnerie d’alarme',
      'vibrate_alert': 'Vibration lors de l’alerte',
      'test_sound_button': '🔔 Tester alarme et notification',
      'backup_and_restore': 'Sauvegarde et Restauration',
      'export_backup': 'Exporter les alertes (JSON)',
      'restore_backup': 'Restaurer les alertes (JSON)',
      'clear_history': 'Effacer l’historique des notifications',
      'battery_settings': 'Optimisation de la batterie (Android)',
      'battery_active': 'Exempté de l’optimisation de batterie',
      'battery_request': 'Demander l’exemption',
      'test_alert_title': 'Notification de test Alarmer',
      'test_alert_body': 'Le son et la notification ont été déclenchés avec succès !',
      'backup_copied': '✅ Sauvegarde copiée dans le presse-papiers.',
      'restore_success': 'Alertes restaurées avec succès.',
      'exchange': 'Plateforme',
      'pair': 'Paire de marché',
      'create_alert_title': 'Créer une alerte intelligente',
      'frequency': 'Fréquence',
      'seconds': 'Sec',
      'minutes': 'Min',
      'hours': 'Heures',
      'empty_alerts_title': 'Aucune alerte configurée',
      'empty_alerts_desc': 'Configurez des alertes de pourcentage ou de prix cible pour crypto, obligations ou actions.',
      'create_first_alert': 'Créer une première alerte',
      'choose_market_step': 'Étape 1 : Choisir le type de marché',
      'choose_market_title': 'Quel marché souhaitez-vous suivre ?',
      'choose_market_desc': 'Sélectionnez le marché et l’actif souhaités.',
      'crypto_market_title': '⚡ Marché Crypto (Cryptomonnaies)',
      'crypto_market_badge': 'Plus de 40 plateformes vérifiées',
      'crypto_market_desc': 'Plus de 40 plateformes internationales et locales avec filtres de catégories.',
      'crypto_market_cta': 'Accéder aux plateformes Crypto →',
      'macro_market_title': '🏛️ Actions US, Obligations & Forex',
      'macro_market_badge': 'Wall Street & Macroéconomie',
      'macro_market_desc': 'Rendements US à 10 ans (US10Y), Forex, actions Nasdaq/NYSE & Or.',
      'macro_market_cta': 'Accéder aux marchés mondiaux →',
      'search_exchange_hint': 'Rechercher une plateforme (Binance, KuCoin)...',
      'search_crypto_hint': 'Rechercher crypto (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Rechercher symbole (US10Y, EUR/USD, NVDA, Or)...',
      'refresh_list': 'Actualiser les paires',
      'select_cta': 'Sélectionner →',
      'selected_asset': 'Actif sélectionné :',
      'auto_check_schedule': '1. Fréquence de vérification :',
      'unit_count': 'Valeur',
      'time_unit': 'Unité de temps',
      'condition_type': '2. Type de condition d’alerte :',
      'percent_change': 'Variation en pourcentage (%)',
      'price_target': 'Prix cible (\$)',
      'price_direction': 'Direction du prix :',
      'both_ways': '± Deux sens',
      'above_only': '▲ Hausse seulement',
      'below_only': '▼ Baisse seulement',
      'target_price_label': 'Prix cible (\$)',
      'percent_label': 'Pourcentage ciblé (%)',
      'save_alert_cta': 'Enregistrer et lancer le suivi',
      'just_now': 'À l’instant',
      'seconds_ago': 'il y a s',
      'minutes_ago': 'il y a m',
      'hours_ago': 'il y a h',
      'days_ago': 'il y a j',
      'every': 'Chaque',
      'cancel': 'Annuler',
      'confirm': 'Confirmer',
      'restore_dialog_hint': 'Collez le texte JSON de sauvegarde ci-dessous :',
      'restore_dialog_btn': 'Confirmer et Restaurer',
      'clear_history_confirm': 'Voulez-vous vraiment effacer tout l’historique des notifications ?',
      'clear_history_btn': 'Tout effacer',
      'clear_history_success': 'L’historique des notifications a été effacé.',
      'battery_exempt_active': 'Actif (les alertes s’exécutent ponctuellement)',
      'battery_exempt_inactive': 'Inactif (les tâches de fond peuvent être suspendues)',
      'battery_exempt_title': 'Exemption d’optimisation de batterie',
      'battery_exempt_success': 'Exemption accordée avec succès.',
      'export_backup_desc': 'Exporter toutes les alertes en format JSON',
      'restore_backup_desc': 'Restaurer les alertes depuis un texte JSON',
      'clear_history_desc': 'Supprimer tous les journaux enregistrés',
      'filter_all': 'Tous',
      'filter_triggered': 'Déclenchés',
      'filter_suppressed': 'Supprimés',
      'no_history_title': 'Aucun historique enregistré',
      'no_history_desc': 'Lorsque les conditions d’alerte sont remplies, les événements apparaîtront ici.',
      'check_price_done': 'Vérification du prix terminée : ',
      'alert_deleted_msg': 'Alerte supprimée : ',
      'undo_action': 'Annuler',
      'target_price_required': 'Veuillez entrer un prix cible',
      'all_symbols': 'Tous les actifs',
      'us_bonds': '🏛️ Obligations du Trésor US',
      'forex_pairs': '💱 Paires Forex',
      'gold_metals': '🥇 Or & Métaux',
      'wallstreet_stocks': '📈 Actions Wall Street',
      'global_indices': '🌐 Indices Mondiaux',
      'price_cross_above': 'Franchir à la hausse (▲)',
      'price_cross_below': 'Chuter à la baisse (▼)',
      'price_cross_direction': 'Direction de franchissement :',
      'above_target': '▲ Au-dessus de la cible',
      'below_target': '▼ En-dessous de la cible',
      'price_fluctuation': 'Variation de prix :',
      'price_surge': 'Hausse de prix :',
      'price_drop': 'Baisse de prix :',
      'target_price_summary': 'Prix cible :',
      'price_delta_summary': 'Delta de prix :',
      'volume_surge_summary': 'Pic de volume :',
      'interval_prefix': '⏱️ La vérification automatique s’exécute chaque ',
      'interval_suffix': ' en arrière-plan.',
    },

    // 7. SPANISH (Español - LTR)
    'es': {
      'my_alerts': 'Mis Alertas',
      'history': 'Historial',
      'settings': 'Ajustes',
      'smart_alerts_desc': 'Monitoreo inteligente según cronograma personalizado',
      'new_alert': 'Nueva Alerta',
      'last_checked_price': 'Último precio verificado:',
      'check_now': 'Verificar ahora',
      'baseline': 'Base',
      'rearm': 'Reactivar Alerta',
      'theme_and_colors': 'Tema y Colores',
      'theme_dark_green': 'Esmeralda Oscuro (Predeterminado)',
      'theme_light_green': 'Esmeralda Claro',
      'theme_dark_orange': 'Naranja Oscuro',
      'theme_light_orange': 'Naranja Claro',
      'select_language': 'Idioma',
      'sound_and_vibrate': 'Sonido y Vibración',
      'sound_alert': 'Sonido de Alarma',
      'vibrate_alert': 'Vibración de Alerta',
      'test_sound_button': '🔔 Probar Alarma y Notificación',
      'backup_and_restore': 'Copia de Seguridad y Restauración',
      'export_backup': 'Exportar Alertas (JSON)',
      'restore_backup': 'Restaurar Alertas (JSON)',
      'clear_history': 'Borrar Historial de Notificaciones',
      'battery_settings': 'Optimización de Batería (Android)',
      'battery_active': 'Exento de optimización de batería',
      'battery_request': 'Solicitar Exención',
      'test_alert_title': 'Notificación de Prueba Alarmer',
      'test_alert_body': '¡El sonido y la notificación se activaron correctamente en su dispositivo!',
      'backup_copied': '✅ Copia de seguridad copiada al portapapeles.',
      'restore_success': 'Alertas restauradas con éxito.',
      'exchange': 'Exchange',
      'pair': 'Par de Mercado',
      'create_alert_title': 'Crear Alerta Inteligente',
      'frequency': 'Frecuencia',
      'seconds': 'Seg',
      'minutes': 'Min',
      'hours': 'Horas',
      'empty_alerts_title': 'Aún no hay alertas configuradas',
      'empty_alerts_desc': 'Configure alertas de cambio porcentual o precio objetivo para criptomonedas, bonos o acciones.',
      'create_first_alert': 'Crear Primera Alerta',
      'choose_market_step': 'Paso 1: Elegir Tipo de Mercado',
      'choose_market_title': '¿Qué mercado desea monitorear?',
      'choose_market_desc': 'Seleccione el tipo de mercado y el activo deseado.',
      'crypto_market_title': '⚡ Mercado Cripto (Criptomonedas)',
      'crypto_market_badge': 'Más de 40 exchanges verificados',
      'crypto_market_desc': 'Más de 40 exchanges internacionales con filtros de categorías y detección de pares.',
      'crypto_market_cta': 'Entrar a Exchanges Cripto →',
      'macro_market_title': '🏛️ Acciones EE. UU., Bonos y Forex',
      'macro_market_badge': 'Wall Street y Macroeconomía',
      'macro_market_desc': 'Rendimientos de bonos a 10 años (US10Y), Forex, acciones Nasdaq/NYSE y Oro.',
      'macro_market_cta': 'Entrar a Mercados Globales →',
      'search_exchange_hint': 'Buscar exchange (Binance, KuCoin)...',
      'search_crypto_hint': 'Buscar cripto (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Buscar símbolo (US10Y, EUR/USD, NVDA, Oro)...',
      'refresh_list': 'Actualizar Pares',
      'select_cta': 'Seleccionar →',
      'selected_asset': 'Activo seleccionado:',
      'auto_check_schedule': '1. Frecuencia de verificación automática:',
      'unit_count': 'Valor',
      'time_unit': 'Unidad de tiempo',
      'condition_type': '2. Tipo de condición de alerta:',
      'percent_change': 'Cambio porcentual (%)',
      'price_target': 'Precio objetivo (\$)',
      'price_direction': 'Dirección del precio:',
      'both_ways': '± Ambos sentidos',
      'above_only': '▲ Solo aumento',
      'below_only': '▼ Solo disminución',
      'target_price_label': 'Precio objetivo (\$)',
      'percent_label': 'Porcentaje deseado (%)',
      'save_alert_cta': 'Guardar e iniciar monitoreo',
      'just_now': 'Justo ahora',
      'seconds_ago': 'hace s',
      'minutes_ago': 'hace m',
      'hours_ago': 'hace h',
      'days_ago': 'hace d',
      'every': 'Cada',
      'cancel': 'Cancelar',
      'confirm': 'Confirmar',
      'restore_dialog_hint': 'Pegue el texto JSON de la copia de seguridad a continuación:',
      'restore_dialog_btn': 'Confirmar y Restaurar',
      'clear_history_confirm': '¿Está seguro de que desea borrar todo el historial de notificaciones?',
      'clear_history_btn': 'Borrar Todo',
      'clear_history_success': 'Se ha borrado el historial de notificaciones.',
      'battery_exempt_active': 'Activo (Las alertas se ejecutan puntualmente)',
      'battery_exempt_inactive': 'Inactivo (El sistema puede pausar tareas en segundo plano)',
      'battery_exempt_title': 'Exención de Optimización de Batería',
      'battery_exempt_success': 'Exención otorgada correctamente.',
      'export_backup_desc': 'Exportar todas las alertas a un archivo JSON',
      'restore_backup_desc': 'Importar alertas desde un texto JSON',
      'clear_history_desc': 'Eliminar todos los registros guardados',
      'filter_all': 'Todos',
      'filter_triggered': 'Activados',
      'filter_suppressed': 'Suprimidos',
      'no_history_title': 'Sin historial registrado',
      'no_history_desc': 'Cuando se cumplan las condiciones de alerta, los eventos aparecerán aquí.',
      'check_price_done': 'Verificación de precio completada: ',
      'alert_deleted_msg': 'Alerta eliminada: ',
      'undo_action': 'Deshacer',
      'target_price_required': 'Por favor ingrese un precio objetivo',
      'all_symbols': 'Todos los activos',
      'us_bonds': '🏛️ Bonos del Tesoro EE. UU.',
      'forex_pairs': '💱 Pares Forex',
      'gold_metals': '🥇 Oro y Metales',
      'wallstreet_stocks': '📈 Acciones de Wall Street',
      'global_indices': '🌐 Índices Globales',
      'price_cross_above': 'Cruzar hacia arriba (▲)',
      'price_cross_below': 'Caer hacia abajo (▼)',
      'price_cross_direction': 'Dirección de cruce:',
      'above_target': '▲ Sobre el objetivo',
      'below_target': '▼ Debajo del objetivo',
      'price_fluctuation': 'Cambio de precio:',
      'price_surge': 'Aumento de precio:',
      'price_drop': 'Caída de precio:',
      'target_price_summary': 'Precio objetivo:',
      'price_delta_summary': 'Delta de precio:',
      'volume_surge_summary': 'Aumento de volumen:',
      'interval_prefix': '⏱️ La verificación de precio se ejecuta cada ',
      'interval_suffix': ' en segundo plano.',
    },

    // 8. TURKISH (Türkçe - LTR)
    'tr': {
      'my_alerts': 'Alarmlarım',
      'history': 'Geçmiş',
      'settings': 'Ayarlar',
      'smart_alerts_desc': 'Özel zamanlamaya göre akıllı fiyat takibi',
      'new_alert': 'Yeni Alarm Ekle',
      'last_checked_price': 'Son Kontrol Edilen Fiyat:',
      'check_now': 'Şimdi Kontrol Et',
      'baseline': 'Baz',
      'rearm': 'Yeniden Kur',
      'theme_and_colors': 'Tema ve Renkler',
      'theme_dark_green': 'Koyu Zümrüt (Varsayılan)',
      'theme_light_green': 'Açık Zümrüt',
      'theme_dark_orange': 'Koyu Turuncu',
      'theme_light_orange': 'Açık Turuncu',
      'select_language': 'Uygulama Dili',
      'sound_and_vibrate': 'Ses ve Titreşim',
      'sound_alert': 'Alarm Sesi',
      'vibrate_alert': 'Alarm Titreşimi',
      'test_sound_button': '🔔 Alarm ve Bildirimi Test Et',
      'backup_and_restore': 'Yedekleme ve Geri Yükleme',
      'export_backup': 'Alarmları Dışa Aktar (JSON)',
      'restore_backup': 'Alarmları Geri Yükle (JSON)',
      'clear_history': 'Bildirim Geçmişini Temizle',
      'battery_settings': 'Pil Optimizasyonu (Android)',
      'battery_active': 'Pil optimizasyonundan muaf',
      'battery_request': 'Muafiyet İste',
      'test_alert_title': 'Alarmer Test Bildirimi',
      'test_alert_body': 'Ses ve bildirim cihazınızda başarıyla tetiklendi!',
      'backup_copied': '✅ Yedek başarıyla panoya kopyalandı.',
      'restore_success': 'Alarmlar başarıyla geri yüklendi.',
      'exchange': 'Borsa',
      'pair': 'Piyasa Çifti',
      'create_alert_title': 'Akıllı Alarm Oluştur',
      'frequency': 'Sıklık',
      'seconds': 'Sn',
      'minutes': 'Dk',
      'hours': 'Saat',
      'empty_alerts_title': 'Henüz alarm yapılandırılmadı',
      'empty_alerts_desc': 'Kripto, ABD tahvilleri veya hisse senetleri için yüzde değişimi veya hedef fiyat alarmları ayarlayabilirsiniz.',
      'create_first_alert': 'İlk Akıllı Alarmı Oluştur',
      'choose_market_step': '1. Adım: Piyasa Türü Seçin',
      'choose_market_title': 'Hangi piyasayı takip etmek istersiniz?',
      'choose_market_desc': 'Fiyatları doğru şekilde izlemek için piyasa türünü ve varlığı seçin.',
      'crypto_market_title': '⚡ Kripto Piyasası (Kripto Paralar)',
      'crypto_market_badge': '40+ Doğrulanmış Borsa',
      'crypto_market_desc': 'Kategori filtreleri ve çift algılama özellikli 40’tan fazla borsa.',
      'crypto_market_cta': 'Kripto Borsalarına Gir →',
      'macro_market_title': '🏛️ ABD Hisseleri, Tahviller ve Forex',
      'macro_market_badge': 'Wall Street ve Makroekonomi',
      'macro_market_desc': 'ABD 10 Yıllık Tahvilleri (US10Y), Forex çiftleri, Nasdaq/NYSE hisseleri ve Altın.',
      'macro_market_cta': 'Küresel Piyasalara Gir →',
      'search_exchange_hint': 'Borsa ara (Binance, KuCoin)...',
      'search_crypto_hint': 'Kripto ara (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': 'Sembol ara (US10Y, EUR/USD, NVDA, Altın)...',
      'refresh_list': 'Çiftleri Yenile',
      'select_cta': 'Seç →',
      'selected_asset': 'Seçilen Varlık:',
      'auto_check_schedule': '1. Otomatik Kontrol Sıklığı:',
      'unit_count': 'Değer',
      'time_unit': 'Zaman Birimi',
      'condition_type': '2. Alarm Koşul Türü:',
      'percent_change': 'Yüzde Değişimi (%)',
      'price_target': 'Hedef Fiyat (\$)',
      'price_direction': 'Fiyat Yönü:',
      'both_ways': '± İki Yöne de',
      'above_only': '▲ Sadece Yükseliş',
      'below_only': '▼ Sadece Düşüş',
      'target_price_label': 'Hedef Fiyat (\$)',
      'percent_label': 'Hedef Yüzde (%)',
      'save_alert_cta': 'Kaydet ve Takibi Başlat',
      'just_now': 'Az önce',
      'seconds_ago': 'sn önce',
      'minutes_ago': 'dk önce',
      'hours_ago': 'saat önce',
      'days_ago': 'gün önce',
      'every': 'Her',
      'cancel': 'İptal',
      'confirm': 'Onayla',
      'restore_dialog_hint': 'Yedek JSON metnini aşağıdaki kutuya yapıştırın:',
      'restore_dialog_btn': 'Onayla ve Geri Yükle',
      'clear_history_confirm': 'Tüm bildirim geçmişini silmek istediğinize emin misiniz?',
      'clear_history_btn': 'Tümünü Temizle',
      'clear_history_success': 'Bildirim geçmişi temizlendi.',
      'battery_exempt_active': 'Aktif (Alarmlar tam vaktinde çalışır)',
      'battery_exempt_inactive': 'Pasif (Arka plan görevleri durdurulabilir)',
      'battery_exempt_title': 'Pil Optimizasyonu Muafiyeti',
      'battery_exempt_success': 'Muafiyet başarıyla verildi.',
      'export_backup_desc': 'Tüm alarmları JSON dosyasına aktar',
      'restore_backup_desc': 'JSON metninden alarmları geri yükle',
      'clear_history_desc': 'Kayıtlı tüm geçmişi sil',
      'filter_all': 'Tümü',
      'filter_triggered': 'Tetiklenenler',
      'filter_suppressed': 'Engellenenler',
      'no_history_title': 'Henüz geçmiş kaydedilmedi',
      'no_history_desc': 'Alarm koşulları gerçekleştiğinde olaylar burada listelenir.',
      'check_price_done': 'Fiyat kontrolü tamamlandı: ',
      'alert_deleted_msg': 'Alarm silindi: ',
      'undo_action': 'Geri Al',
      'target_price_required': 'Lütfen bir hedef fiyat girin',
      'all_symbols': 'Tüm Varlıklar',
      'us_bonds': '🏛️ ABD Hazine Tahvilleri',
      'forex_pairs': '💱 Forex Çiftleri',
      'gold_metals': '🥇 Altın ve Metaller',
      'wallstreet_stocks': '📈 Wall Street Hisseleri',
      'global_indices': '🌐 Küresel Endeksler',
      'price_cross_above': 'Yukarı geçiş (▲)',
      'price_cross_below': 'Aşağı düşüş (▼)',
      'price_cross_direction': 'Geçiş Yönü:',
      'above_target': '▲ Hedefin Üzerinde',
      'below_target': '▼ Hedefin Altında',
      'price_fluctuation': 'Fiyat değişimi:',
      'price_surge': 'Fiyat artışı:',
      'price_drop': 'Fiyat düşüşü:',
      'target_price_summary': 'Hedef fiyat:',
      'price_delta_summary': 'Fiyat farkı:',
      'volume_surge_summary': 'Hacim sıçraması:',
      'interval_prefix': '⏱️ Otomatik fiyat kontrolü her ',
      'interval_suffix': ' bir kez arka planda çalışır.',
    },

    // 9. CHINESE (中文 - LTR)
    'zh': {
      'my_alerts': '我的预警',
      'history': '历史记录',
      'settings': '设置',
      'smart_alerts_desc': '按自定义计划进行智能价格监控',
      'new_alert': '添加新预警',
      'last_checked_price': '最后检查价格：',
      'check_now': '立即检查',
      'baseline': '基准',
      'rearm': '重新启用',
      'theme_and_colors': '主题与颜色',
      'theme_dark_green': '暗夜翡翠（默认）',
      'theme_light_green': '明亮翡翠',
      'theme_dark_orange': '暗夜橙',
      'theme_light_orange': '明亮橙',
      'select_language': '语言',
      'sound_and_vibrate': '声音与震动',
      'sound_alert': '警报声音',
      'vibrate_alert': '预警震动',
      'test_sound_button': '🔔 测试警报与通知',
      'backup_and_restore': '备份与恢复',
      'export_backup': '导出预警备份 (JSON)',
      'restore_backup': '恢复预警 (JSON)',
      'clear_history': '清除通知历史',
      'battery_settings': '电池优化（Android）',
      'battery_active': '已豁免电池优化（准时执行）',
      'battery_request': '请求豁免',
      'test_alert_title': 'Alarmer 测试通知',
      'test_alert_body': '声音和通知已在您的设备上成功触发！',
      'backup_copied': '✅ 备份已成功复制到剪贴板。',
      'restore_success': '预警已成功恢复。',
      'exchange': '交易所',
      'pair': '交易对',
      'create_alert_title': '创建智能预警',
      'frequency': '检查频率',
      'seconds': '秒',
      'minutes': '分钟',
      'hours': '小时',
      'empty_alerts_title': '尚未配置任何预警',
      'empty_alerts_desc': '您可以为任何加密货币、美债或全球股票设置百分比或目标价预警。',
      'create_first_alert': '创建第一个预警',
      'choose_market_step': '第一步：选择市场类型',
      'choose_market_title': '您想跟踪哪个市场？',
      'choose_market_desc': '选择市场类型和目标资产以进行精准监控。',
      'crypto_market_title': '⚡ 加密货币市场 (Crypto)',
      'crypto_market_badge': '40+ 家经过验证的交易所',
      'crypto_market_desc': '超过 40 家顶级交易所，提供分类筛选和交易对自动发现功能。',
      'crypto_market_cta': '进入加密交易所 →',
      'macro_market_title': '🏛️ 美股、美国国债与外汇',
      'macro_market_badge': '华尔街与宏观经济',
      'macro_market_desc': '美国 10 年期国债收益率 (US10Y)、外汇、纳斯达克/纽交所股票和黄金。',
      'macro_market_cta': '进入全球市场 →',
      'search_exchange_hint': '搜索交易所 (Binance, KuCoin)...',
      'search_crypto_hint': '搜索加密货币 (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': '搜索资产 (US10Y, EUR/USD, 黄金)...',
      'refresh_list': '刷新交易对',
      'select_cta': '选择 →',
      'selected_asset': '已选资产：',
      'auto_check_schedule': '1. 自动检查计划：',
      'unit_count': '间隔数值',
      'time_unit': '时间单位',
      'condition_type': '2. 预警条件类型：',
      'percent_change': '百分比变化 (%)',
      'price_target': '目标价格 (\$)',
      'price_direction': '价格方向：',
      'both_ways': '± 双向波动',
      'above_only': '▲ 仅上涨',
      'below_only': '▼ 仅下跌',
      'target_price_label': '目标价格 (美元)',
      'percent_label': '目标百分比 (%)',
      'save_alert_cta': '保存并开始监控',
      'just_now': '刚刚',
      'seconds_ago': '秒前',
      'minutes_ago': '分钟前',
      'hours_ago': '小时前',
      'days_ago': '天前',
      'every': '每',
      'cancel': '取消',
      'confirm': '确认',
      'restore_dialog_hint': '将导出的 JSON 备份文本粘贴在下方：',
      'restore_dialog_btn': '确认并恢复',
      'clear_history_confirm': '确定要清除所有通知历史记录吗？',
      'clear_history_btn': '清除全部',
      'clear_history_success': '所有通知历史记录已被清除。',
      'battery_exempt_active': '已激活（后台准时触发）',
      'battery_exempt_inactive': '未激活（系统可能会休眠后台任务）',
      'battery_exempt_title': '电池优化豁免',
      'battery_exempt_success': '电池豁免请求成功。',
      'export_backup_desc': '导出所有预警为 JSON 格式',
      'restore_backup_desc': '从 JSON 文本恢复预警',
      'clear_history_desc': '删除所有已保存的历史日志',
      'filter_all': '全部',
      'filter_triggered': '已触发',
      'filter_suppressed': '已抑制',
      'no_history_title': '暂无历史记录',
      'no_history_desc': '触发预警条件后，相关事件会记录在这里。',
      'check_price_done': '价格检查完成：',
      'alert_deleted_msg': '预警已删除：',
      'undo_action': '撤销',
      'target_price_required': '请输入目标价格',
      'all_symbols': '所有资产',
      'us_bonds': '🏛️ 美国国债',
      'forex_pairs': '💱 外汇货币对',
      'gold_metals': '🥇 黄金与贵金属',
      'wallstreet_stocks': '📈 华尔街股票',
      'global_indices': '🌐 全球指数',
      'price_cross_above': '向上突破 (▲)',
      'price_cross_below': '跌破目标 (▼)',
      'price_cross_direction': '穿越方向：',
      'above_target': '▲ 高于目标',
      'below_target': '▼ 低于目标',
      'price_fluctuation': '价格波动：',
      'price_surge': '价格上涨：',
      'price_drop': '价格下跌：',
      'target_price_summary': '目标价格：',
      'price_delta_summary': '价格差额：',
      'volume_surge_summary': '成交量激增：',
      'interval_prefix': '⏱️ 后台自动价格检查每 ',
      'interval_suffix': ' 执行一次。',
    },

    // 10. KOREAN (한국어 - LTR)
    'ko': {
      'my_alerts': '내 알림',
      'history': '히스토리',
      'settings': '설정',
      'smart_alerts_desc': '사용자 지정 일정에 따른 지능형 가격 모니터링',
      'new_alert': '새 알림 추가',
      'last_checked_price': '마지막 확인 가격:',
      'check_now': '지금 확인',
      'baseline': '기준가',
      'rearm': '알림 재활성화',
      'theme_and_colors': '테마 및 색상',
      'theme_dark_green': '다크 에메랄드 (기본)',
      'theme_light_green': '라이트 에메랄드',
      'theme_dark_orange': '다크 오렌지',
      'theme_light_orange': '라이트 오렌지',
      'select_language': '언어',
      'sound_and_vibrate': '소리 및 진동',
      'sound_alert': '알람 소리',
      'vibrate_alert': '알림 진동',
      'test_sound_button': '🔔 알람 및 알림 테스트',
      'backup_and_restore': '백업 및 복원',
      'export_backup': '알림 내보내기 (JSON)',
      'restore_backup': '알림 복원 (JSON)',
      'clear_history': '알림 기록 삭제',
      'battery_settings': '배터리 최적화 (Android)',
      'battery_active': '배터리 최적화 예외됨 (정시 실행)',
      'battery_request': '예외 요청',
      'test_alert_title': 'Alarmer 테스트 알림',
      'test_alert_body': '기기에서 소리와 알림이 성공적으로 실행되었습니다!',
      'backup_copied': '✅ 백업이 클립보드에 복사되었습니다.',
      'restore_success': '알림이 성공적으로 복원되었습니다.',
      'exchange': '거래소',
      'pair': '거래쌍',
      'create_alert_title': '스마트 알림 만들기',
      'frequency': '확인 주기',
      'seconds': '초',
      'minutes': '분',
      'hours': '시간',
      'empty_alerts_title': '설정된 알림이 없습니다',
      'empty_alerts_desc': '암호화폐, 미국 국채, 글로벌 주식에 대해 변동률 또는 목표가 알림을 설정할 수 있습니다.',
      'create_first_alert': '첫 번째 스마트 알림 만들기',
      'choose_market_step': '1단계: 시장 유형 선택',
      'choose_market_title': '어떤 시장을 추적하시겠습니까?',
      'choose_market_desc': '정확한 모니터링을 위해 시장과 자산을 선택하세요.',
      'crypto_market_title': '⚡ 암호화폐 시장 (Crypto)',
      'crypto_market_badge': '40개 이상의 검증된 거래소',
      'crypto_market_desc': '카테고리 필터와 거래쌍 자동 감지 기능이 있는 40개 이상의 주요 거래소.',
      'crypto_market_cta': '암호화폐 거래소 입장 →',
      'macro_market_title': '🏛️ 미국 주식, 국채 및 외환',
      'macro_market_badge': '월스트리트 & 거시 경제',
      'macro_market_desc': '미국 10년물 국채(US10Y), 외환, 나스닥/NYSE 주식 및 금.',
      'macro_market_cta': '글로벌 시장 입장 →',
      'search_exchange_hint': '거래소 검색 (Binance, KuCoin)...',
      'search_crypto_hint': '암호화폐 검색 (BTC, ETH, SOL, DOGE)...',
      'search_macro_hint': '심볼 검색 (US10Y, EUR/USD, 금)...',
      'refresh_list': '목록 새로고침',
      'select_cta': '선택 →',
      'selected_asset': '선택된 자산:',
      'auto_check_schedule': '1. 자동 확인 주기:',
      'unit_count': '값',
      'time_unit': '시간 단위',
      'condition_type': '2. 알림 조건 유형:',
      'percent_change': '변동률 (%)',
      'price_target': '목표 가격 (\$)',
      'price_direction': '가격 방향:',
      'both_ways': '± 양방향',
      'above_only': '▲ 상승 시에만',
      'below_only': '▼ 하락 시에만',
      'target_price_label': '목표 가격 (달러)',
      'percent_label': '목표 퍼센트 (%)',
      'save_alert_cta': '저장 및 모니터링 시작',
      'just_now': '방금 전',
      'seconds_ago': '초 전',
      'minutes_ago': '분 전',
      'hours_ago': '시간 전',
      'days_ago': '일 전',
      'every': '매',
      'cancel': '취소',
      'confirm': '확인',
      'restore_dialog_hint': '백업된 JSON 텍스트를 아래 입력창에 붙여넣으세요:',
      'restore_dialog_btn': '확인 및 복원',
      'clear_history_confirm': '모든 알림 히스토리를 삭제하시겠습니까?',
      'clear_history_btn': '모두 삭제',
      'clear_history_success': '알림 히스토리가 삭제되었습니다.',
      'battery_exempt_active': '활성화됨 (알림이 제시간에 실행됨)',
      'battery_exempt_inactive': '비활성화됨 (백그라운드 작업이 중지될 수 있음)',
      'battery_exempt_title': '배터리 최적화 예외',
      'battery_exempt_success': '배터리 예외가 성공적으로 승인되었습니다.',
      'export_backup_desc': '모든 활성 알림을 JSON 파일로 내보내기',
      'restore_backup_desc': 'JSON 텍스트에서 알림 가져오기',
      'clear_history_desc': '저장된 모든 알림 기록 삭제',
      'filter_all': '전체',
      'filter_triggered': '실행됨',
      'filter_suppressed': '제한됨',
      'no_history_title': '기록된 히스토리가 없습니다',
      'no_history_desc': '알림 조건이 충족되면 이벤트가 여기에 기록됩니다.',
      'check_price_done': '가격 확인 완료: ',
      'alert_deleted_msg': '알림 삭제됨: ',
      'undo_action': '실행 취소',
      'target_price_required': '목표 가격을 입력하세요',
      'all_symbols': '모든 자산',
      'us_bonds': '🏛️ 미국 국채',
      'forex_pairs': '💱 외환 통화쌍',
      'gold_metals': '🥇 금 및 귀금속',
      'wallstreet_stocks': '📈 월스트리트 주식',
      'global_indices': '🌐 글로벌 지수',
      'price_cross_above': '상승 돌파 (▲)',
      'price_cross_below': '하락 돌파 (▼)',
      'price_cross_direction': '돌파 방향:',
      'above_target': '▲ 목표가 초과',
      'below_target': '▼ 목표가 미만',
      'price_fluctuation': '가격 변동:',
      'price_surge': '가격 상승:',
      'price_drop': '가격 하락:',
      'target_price_summary': '목표 가격:',
      'price_delta_summary': '가격 차이:',
      'volume_surge_summary': '거래량 급증:',
      'interval_prefix': '⏱️ 자동 가격 확인이 백그라운드에서 매 ',
      'interval_suffix': '마다 실행됩니다.',
    },
  };

  static String get(String key, [String lang = 'fa']) {
    final langMap = _translations[lang] ?? _translations['fa']!;
    return langMap[key] ?? _translations['en']?[key] ?? _translations['fa']?[key] ?? key;
  }
}
