/// Multilingual dictionary supporting 10 languages
class AppStrings {
  static final Map<String, Map<String, String>> _translations = {
    'fa': {
      'my_alerts': 'هشدارهای من',
      'history': 'تاریخچه',
      'settings': 'تنظیمات',
      'smart_alerts_desc': 'بررسی هوشمند بر اساس زمان‌بندی دلخواه',
      'new_alert': 'افزودن هشدار جدید',
      'last_checked_price': 'آخرین قیمت بررسی‌شده:',
      'check_now': 'بررسی آنی',
      'baseline': 'مبنا',
      'rearm': 'فعال‌سازی مجدد',
      'theme_and_colors': 'پوسته و رنگ‌بندی',
      'theme_dark_green': 'دارک سبز (پیش‌فرض)',
      'theme_light_green': 'لایت سبز',
      'theme_dark_orange': 'دارک نارنجی',
      'theme_light_orange': 'لایت نارنجی',
      'select_language': 'زبان برنامه',
      'sound_and_vibrate': 'صدا و لرزش (Sound & Haptics)',
      'sound_alert': 'صدای هشدار و آلارم',
      'vibrate_alert': 'ویبره هنگام هشدار',
      'test_sound_button': '🔔 تست صدای آلارم و نوتیفیکیشن',
      'backup_and_restore': 'پشتیبان‌گیری و بازیابی',
      'export_backup': 'پشتیبان‌گیری از هشدارها (Export)',
      'restore_backup': 'بازیابی هشدارها (Restore)',
      'clear_history': 'پاک‌سازی تاریخچه اعلان‌ها',
      'battery_settings': 'بهینه‌سازی باتری در پس‌زمینه (Android)',
      'battery_active': 'معاف از بهینه‌سازی باتری (اجرای مطمئن)',
      'battery_request': 'درخواست معافیت باتری',
      'test_alert_title': 'تست سامانه هشدار Alarmer',
      'test_alert_body': 'صدا و اعلان تستی با موفقیت روی دستگاه شما به صدا درآمد!',
      'backup_copied': '✅ پشتیبان‌گیری انجام شد و در کلیپ‌بورد کپی گردید.',
      'restore_success': '🎉 هشدارها با موفقیت بازیابی شدند.',
      'exchange': 'صرافی',
      'pair': 'جفت‌ارز',
      'create_alert_title': 'ایجاد هشدار هوشمند',
      'frequency': 'دوره بررسی',
      'seconds': 'ثانیه',
      'minutes': 'دقیقه',
      'hours': 'ساعت',
      'empty_alerts_title': 'هنوز هشداری تنظیم نشده است',
      'empty_alerts_desc': 'می‌توانید برای هر ارز دیجیتال، اوراق قرضه آمریکا یا سهام جهانی هشدار تنظیم کنید.',
      'create_first_alert': 'ایجاد اولین هشدار هوشمند',
      'choose_market_step': 'گام نخست: انتخاب نوع بازار',
      'choose_market_title': 'مایلید برای کدام بازار هشدار تنظیم کنید؟',
      'choose_market_desc': 'نوع بازار و دارایی مورد نظر خود را برای پایش دقیق قیمت انتخاب نمایید.',
      'crypto_market_title': '⚡ بازار رمزارزها (کریپتو)',
      'crypto_market_badge': 'بیش از ۴۰ صرافی معتبر',
      'crypto_market_desc': 'بیش از ۴۰ صرافی معتبر بین‌المللی و ایرانی با چیپ‌های فیلتر، استخراج جفت‌ارزها و دکمه بروزرسانی',
      'crypto_market_cta': 'ورود به بخش صرافی‌های کریپتو ←',
      'macro_market_title': '🏛️ سهام، اوراق قرضه آمریکا و فارکس',
      'macro_market_badge': 'وال استریت و اقتصاد کلان',
      'macro_market_desc': 'اوراق قرضه ۱۰ ساله آمریکا (US10Y)، جفت‌ارزهای فارکس، سهام‌های نزدک/نیویورک، طلا و شاخص‌ها',
      'macro_market_cta': 'ورود به بازارهای جهانی ←',
      'search_exchange_hint': 'جستجوی صرافی (Binance, Nobitex, KuCoin)...',
      'search_crypto_hint': 'جستجوی رمزارز (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'جستجوی نماد (US10Y, EUR/USD, NVDA, طلا)...',
      'refresh_list': 'بروزرسانی لیست',
      'select_cta': 'انتخاب →',
      'selected_asset': 'دارایی انتخاب‌شده:',
      'auto_check_schedule': '۱. زمان‌بندی بررسی خودکار:',
      'unit_count': 'تعداد واحد',
      'time_unit': 'واحد زمان',
      'condition_type': '۲. نوع شرط هشدار:',
      'percent_change': 'درصد تغییر (%)',
      'price_target': 'قیمت هدف (\$)',
      'price_direction': 'جهت نوسان قیمت:',
      'both_ways': '± هر دو طرف',
      'above_only': '▲ فقط افزایش',
      'below_only': '▼ فقط کاهش',
      'target_price_label': 'قیمت هدف (دلار)',
      'percent_label': 'درصد نوسان مد نظر (%)',
      'save_alert_cta': 'ذخیره و شروع بررسی هشدار',
      'just_now': 'همین الان',
      'seconds_ago': 'ثانیه قبل',
      'minutes_ago': 'دقیقه قبل',
      'hours_ago': 'ساعت قبل',
      'days_ago': 'روز قبل',
      'every': 'هر',
      'condition_prefix': 'شرط هشدار:',
      'exchange_prefix': 'صرافی:',
    },
    'en': {
      'my_alerts': 'My Alerts',
      'history': 'History',
      'settings': 'Settings',
      'smart_alerts_desc': 'Intelligent monitoring based on custom schedule',
      'new_alert': 'Add New Alert',
      'last_checked_price': 'Last Checked Price:',
      'check_now': 'Check Now',
      'baseline': 'Base',
      'rearm': 'Re-arm Alert',
      'theme_and_colors': 'Theme & Color Scheme',
      'theme_dark_green': 'Dark Emerald (Default)',
      'theme_light_green': 'Light Emerald',
      'theme_dark_orange': 'Dark Orange',
      'theme_light_orange': 'Light Orange',
      'select_language': 'Language',
      'sound_and_vibrate': 'Sound & Haptics',
      'sound_alert': 'Alarm Sound',
      'vibrate_alert': 'Vibration Alert',
      'test_sound_button': '🔔 Test Alarm & Notification',
      'backup_and_restore': 'Backup & Restore',
      'export_backup': 'Export Alerts Backup (JSON)',
      'restore_backup': 'Restore Alerts (JSON)',
      'clear_history': 'Clear Notification History',
      'battery_settings': 'Battery Optimization (Android)',
      'battery_active': 'Exempt from battery optimization (Reliable)',
      'battery_request': 'Request Exemption',
      'test_alert_title': 'Alarmer Test Notification',
      'test_alert_body': 'Sound and notification successfully triggered on your device!',
      'backup_copied': '✅ Backup copied to clipboard successfully.',
      'restore_success': '🎉 Alerts restored successfully.',
      'exchange': 'Exchange',
      'pair': 'Market Pair',
      'create_alert_title': 'Create Smart Alert',
      'frequency': 'Frequency',
      'seconds': 'Sec',
      'minutes': 'Min',
      'hours': 'Hours',
      'empty_alerts_title': 'No Alerts Configured Yet',
      'empty_alerts_desc': 'You can set percent change or price target alerts for any crypto, US bond, or global stock.',
      'create_first_alert': 'Create First Smart Alert',
      'choose_market_step': 'Step 1: Choose Market Type',
      'choose_market_title': 'Which market would you like to track?',
      'choose_market_desc': 'Select your desired market type and asset to accurately monitor prices.',
      'crypto_market_title': '⚡ Crypto Market (Cryptocurrencies)',
      'crypto_market_badge': '40+ Verified Exchanges',
      'crypto_market_desc': 'Over 40 top international and Iranian exchanges with category filters and pair auto-discovery.',
      'crypto_market_cta': 'Enter Crypto Exchanges ←',
      'macro_market_title': '🏛️ US Stocks, Treasury Bonds & Forex',
      'macro_market_badge': 'Wall Street & Macro Economy',
      'macro_market_desc': 'US 10-Year Yields (US10Y), Forex pairs, Nasdaq/NYSE equities, Gold & Global Indices.',
      'macro_market_cta': 'Enter Global Markets ←',
      'search_exchange_hint': 'Search exchange (Binance, Nobitex, KuCoin)...',
      'search_crypto_hint': 'Search crypto (BTC, ETH, SOL, POL, DOGE)...',
      'search_macro_hint': 'Search symbol (US10Y, EUR/USD, NVDA, Gold)...',
      'refresh_list': 'Refresh Pairs',
      'select_cta': 'Select →',
      'selected_asset': 'Selected Asset:',
      'auto_check_schedule': '1. Automated Check Schedule:',
      'unit_count': 'Interval Value',
      'time_unit': 'Time Unit',
      'condition_type': '2. Alert Condition Type:',
      'percent_change': 'Percent Change (%)',
      'price_target': 'Price Target (\$)',
      'price_direction': 'Price Direction:',
      'both_ways': '± Both Ways',
      'above_only': '▲ Above Only',
      'below_only': '▼ Below Only',
      'target_price_label': 'Target Price (\$)',
      'percent_label': 'Target Percentage (%)',
      'save_alert_cta': 'Save and Start Monitoring',
      'just_now': 'Just now',
      'seconds_ago': 's ago',
      'minutes_ago': 'm ago',
      'hours_ago': 'h ago',
      'days_ago': 'd ago',
      'every': 'Every',
      'condition_prefix': 'Condition:',
      'exchange_prefix': 'Exchange:',
    },
    'de': {
      'my_alerts': 'Meine Alarme',
      'history': 'Verlauf',
      'settings': 'Einstellungen',
      'smart_alerts_desc': 'Intelligente Überwachung nach Zeitplan',
      'new_alert': 'Neuer Alarm',
      'last_checked_price': 'Letzter Preis:',
      'check_now': 'Jetzt prüfen',
      'baseline': 'Basis',
      'rearm': 'Reaktivieren',
      'theme_and_colors': 'Design & Farben',
      'theme_dark_green': 'Dunkelgrün',
      'theme_light_green': 'Hellgrün',
      'theme_dark_orange': 'Dunkelorange',
      'theme_light_orange': 'Hellorange',
      'select_language': 'Sprache',
      'sound_and_vibrate': 'Ton & Vibration',
      'sound_alert': 'Alarmton',
      'vibrate_alert': 'Vibration',
      'test_sound_button': '🔔 Alarmton testen',
      'backup_and_restore': 'Sicherung & Wiederherstellung',
      'export_backup': 'Sicherung exportieren',
      'restore_backup': 'Wiederherstellen',
      'clear_history': 'Verlauf löschen',
      'battery_settings': 'Batterieoptimierung',
      'battery_active': 'Ausgenommen (Zuverlässig)',
      'battery_request': 'Ausnahme anfordern',
      'test_alert_title': 'Alarmer Testalarm',
      'test_alert_body': 'Ton und Benachrichtigung erfolgreich ausgelöst!',
      'backup_copied': '✅ In die Zwischenablage kopiert.',
      'restore_success': '🎉 Alarme erfolgreich wiederhergestellt.',
      'exchange': 'Börse',
      'pair': 'Währungspaar',
      'create_alert_title': 'Alarm erstellen',
      'frequency': 'Intervall',
      'seconds': 'Sek',
      'minutes': 'Min',
      'hours': 'Std',
    },
    'fr': {
      'my_alerts': 'Mes Alertes',
      'history': 'Historique',
      'settings': 'Paramètres',
      'smart_alerts_desc': 'Surveillance intelligente personnalisée',
      'new_alert': 'Nouvelle alerte',
      'last_checked_price': 'Dernier prix vérifié:',
      'check_now': 'Vérifier',
      'baseline': 'Base',
      'rearm': 'Réactiver',
      'theme_and_colors': 'Thème et couleurs',
      'theme_dark_green': 'Émeraude Sombre',
      'theme_light_green': 'Émeraude Clair',
      'theme_dark_orange': 'Orange Sombre',
      'theme_light_orange': 'Orange Clair',
      'select_language': 'Langue',
      'sound_and_vibrate': 'Son et vibration',
      'sound_alert': 'Son d\'alerte',
      'vibrate_alert': 'Vibration',
      'test_sound_button': '🔔 Tester le son de l\'alarme',
      'backup_and_restore': 'Sauvegarde et restauration',
      'export_backup': 'Exporter la sauvegarde',
      'restore_backup': 'Restaurer',
      'clear_history': 'Effacer l\'historique',
      'battery_settings': 'Optimisation de la batterie',
      'battery_active': 'Exempté (Fiable)',
      'battery_request': 'Demander l\'exemption',
      'test_alert_title': 'Test Alarmer',
      'test_alert_body': 'Notification et son testés avec succès !',
      'backup_copied': '✅ Sauvegarde copiée dans le presse-papiers.',
      'restore_success': '🎉 Alertes restaurées avec succès.',
      'exchange': 'Échange',
      'pair': 'Paire',
      'create_alert_title': 'Créer une alerte',
      'frequency': 'Fréquence',
      'seconds': 'Sec',
      'minutes': 'Min',
      'hours': 'Heures',
    },
    'es': {
      'my_alerts': 'Mis Alertas',
      'history': 'Historial',
      'settings': 'Ajustes',
      'smart_alerts_desc': 'Monitoreo inteligente con intervalo personalizado',
      'new_alert': 'Nueva alerta',
      'last_checked_price': 'Último precio verificado:',
      'check_now': 'Verificar ahora',
      'baseline': 'Base',
      'rearm': 'Reactivar',
      'theme_and_colors': 'Tema y colores',
      'theme_dark_green': 'Esmeralda Oscuro',
      'theme_light_green': 'Esmeralda Claro',
      'theme_dark_orange': 'Naranja Oscuro',
      'theme_light_orange': 'Naranja Claro',
      'select_language': 'Idioma',
      'sound_and_vibrate': 'Sonido y vibración',
      'sound_alert': 'Sonido de alarma',
      'vibrate_alert': 'Vibración',
      'test_sound_button': '🔔 Probar sonido de alarma',
      'backup_and_restore': 'Copia de seguridad',
      'export_backup': 'Exportar copia (JSON)',
      'restore_backup': 'Restaurar alertas',
      'clear_history': 'Borrar historial',
      'battery_settings': 'Optimización de batería',
      'battery_active': 'Exento (Ejecución fiable)',
      'battery_request': 'Solicitar exención',
      'test_alert_title': 'Prueba de Alarmer',
      'test_alert_body': '¡Sonido y notificación emitidos con éxito!',
      'backup_copied': '✅ Copia guardada en el portapapeles.',
      'restore_success': '🎉 Alertas restauradas con éxito.',
      'exchange': 'Exchange',
      'pair': 'Par de divisas',
      'create_alert_title': 'Crear alerta',
      'frequency': 'Frecuencia',
      'seconds': 'Seg',
      'minutes': 'Min',
      'hours': 'Horas',
    },
    'zh': {
      'my_alerts': '我的预警',
      'history': '历史记录',
      'settings': '设置',
      'smart_alerts_desc': '基于自定义时间表的智能监控',
      'new_alert': '新建预警',
      'last_checked_price': '最新检测价格：',
      'check_now': '立即检测',
      'baseline': '基准',
      'rearm': '重新激活',
      'theme_and_colors': '主题与配色',
      'theme_dark_green': '暗夜翡翠（默认）',
      'theme_light_green': '清新绿',
      'theme_dark_orange': '暗夜橙',
      'theme_light_orange': '明亮橙',
      'select_language': '语言',
      'sound_and_vibrate': '声音与震动',
      'sound_alert': '报警声音',
      'vibrate_alert': '报警震动',
      'test_sound_button': '🔔 测试警报声与通知',
      'backup_and_restore': '备份与恢复',
      'export_backup': '导出备份 (JSON)',
      'restore_backup': '导入恢复',
      'clear_history': '清空通知历史',
      'battery_settings': '电池优化设置 (Android)',
      'battery_active': '已豁免优化（确保及时响铃）',
      'battery_request': '申请豁免权限',
      'test_alert_title': 'Alarmer 测试预警',
      'test_alert_body': '测试声音与通知已成功在您的手机触发！',
      'backup_copied': '✅ 备份已成功复制到剪贴板。',
      'restore_success': '🎉 预警规则已成功恢复。',
      'exchange': '交易所',
      'pair': '交易对',
      'create_alert_title': '创建智能预警',
      'frequency': '监控频率',
      'seconds': '秒',
      'minutes': '分钟',
      'hours': '小时',
    },
    'ko': {
      'my_alerts': '내 알림',
      'history': '기록',
      'settings': '설정',
      'smart_alerts_desc': '사용자 지정 일정에 따른 스마트 모니터링',
      'new_alert': '새 알림 추가',
      'last_checked_price': '최근 확인된 가격:',
      'check_now': '지금 확인',
      'baseline': '기준가',
      'rearm': '알림 재활성화',
      'theme_and_colors': '테마 및 색상',
      'theme_dark_green': '다크 에메랄드',
      'theme_light_green': '라이트 에메랄드',
      'theme_dark_orange': '다크 오렌지',
      'theme_light_orange': '라이트 오렌지',
      'select_language': '언어 선택',
      'sound_and_vibrate': '소리 및 진동',
      'sound_alert': '알람 소리',
      'vibrate_alert': '알람 진동',
      'test_sound_button': '🔔 알람 소리 및 알림 테스트',
      'backup_and_restore': '백업 및 복원',
      'export_backup': '백업 내보내기 (JSON)',
      'restore_backup': '백업 복원',
      'clear_history': '알림 기록 지우기',
      'battery_settings': '배터리 최적화 설정',
      'battery_active': '최적화 예외 (신뢰성 높은 실행)',
      'battery_request': '예외 요청',
      'test_alert_title': 'Alarmer 테스트 알림',
      'test_alert_body': '테스트 알람과 소리가 성공적으로 작동했습니다!',
      'backup_copied': '✅ 클립보드에 백업이 복사되었습니다.',
      'restore_success': '🎉 알림이 성공적으로 복원되었습니다.',
      'exchange': '거래소',
      'pair': '통화 쌍',
      'create_alert_title': '스마트 알림 생성',
      'frequency': '모니터링 주기',
      'seconds': '초',
      'minutes': '분',
      'hours': '시간',
    },
    'ckb': {
      'my_alerts': 'ئاگادارییەکانی من',
      'history': 'مێژوو',
      'settings': 'ڕێکخستنەکان',
      'smart_alerts_desc': 'چاودێری زیرەک بەپێی کاتی دیاریکراو',
      'new_alert': 'زیادکردنی ئاگاداری نوێ',
      'last_checked_price': 'دواین نرخی پشکنراو:',
      'check_now': 'پشکنینی دەستبەجێ',
      'baseline': 'بنچینە',
      'rearm': 'دووبارە چالاککردنەوە',
      'theme_and_colors': 'ڕووکار و ڕەنگ',
      'theme_dark_green': 'تاریک سەوز',
      'theme_light_green': 'ڕووناک سەوز',
      'theme_dark_orange': 'تاریک پڕتەقاڵی',
      'theme_light_orange': 'ڕووناک پڕتەقاڵی',
      'select_language': 'زمانی بەرنامە',
      'sound_and_vibrate': 'دەنگ و لەرزین',
      'sound_alert': 'دەنگی ئاگادارکردنەوە',
      'vibrate_alert': 'لەرزین لە کاتی ئاگاداری',
      'test_sound_button': '🔔 تاقیکردنەوەی دەنگ و ئاگاداری',
      'backup_and_restore': 'پاشەکەوت و گەڕاندنەوە',
      'export_backup': 'پاشەکەوتکردن (JSON)',
      'restore_backup': 'گەڕاندنەوەی ئاگادارییەکان',
      'clear_history': 'سڕینەوەی مێژوو',
      'battery_settings': 'ڕێکخستنی باتری',
      'battery_active': 'چالاکە (بەردەوام کاردەکات)',
      'battery_request': 'داواکردنی دەسەڵات',
      'test_alert_title': 'تاقیکردنەوەی Alarmer',
      'test_alert_body': 'دەنگ و ئاگاداری بە سەرکەوتوویی تاقیکرایەوە!',
      'backup_copied': '✅ پاشەکەوت کۆپیکرا.',
      'restore_success': '🎉 ئاگادارییەکان گەڕێنرانەوە.',
      'exchange': 'ئاڵوگۆڕ',
      'pair': 'جووت دراو',
      'create_alert_title': 'دروستکردنی ئاگاداری',
      'frequency': 'ماوەی پشکنین',
      'seconds': 'چرکە',
      'minutes': 'خولەک',
      'hours': 'کاتژمێر',
    },
    'ar': {
      'my_alerts': 'تنبيهاتي',
      'history': 'السجل',
      'settings': 'الإعدادات',
      'smart_alerts_desc': 'مراقبة ذكية بناءً على جدول زمني مخصص',
      'new_alert': 'إضافة تنبيه جديد',
      'last_checked_price': 'آخر سعر تم فحصه:',
      'check_now': 'فحص فوري',
      'baseline': 'الأساس',
      'rearm': 'إعادة التفعيل',
      'theme_and_colors': 'المظهر والألوان',
      'theme_dark_green': 'داكن أخضر (افتراضي)',
      'theme_light_green': 'فاتح أخضر',
      'theme_dark_orange': 'داكن برتقالي',
      'theme_light_orange': 'فاتح برتقالي',
      'select_language': 'لغة التطبيق',
      'sound_and_vibrate': 'الصوت والاهتزاز',
      'sound_alert': 'صوت المنبه',
      'vibrate_alert': 'الاهتزاز عند التنبيه',
      'test_sound_button': '🔔 تجربة الصوت والإشعار',
      'backup_and_restore': 'النسخ الاحتياطي والاستعادة',
      'export_backup': 'تصدير التنبيهات (JSON)',
      'restore_backup': 'استعادة التنبيهات',
      'clear_history': 'مسح سجل الإشعارات',
      'battery_settings': 'تحسين البطارية (Android)',
      'battery_active': 'مستثنى من التقييد (يعمل بدقة)',
      'battery_request': 'طلب الاستثناء',
      'test_alert_title': 'تجربة تنبيه Alarmer',
      'test_alert_body': 'تم إطلاق صوت التنبيه والإشعار بنجاح على جهازك!',
      'backup_copied': '✅ تم نسخ النسخة الاحتياطية بنجاح.',
      'restore_success': '🎉 تمت استعادة التنبيهات بنجاح.',
      'exchange': 'المنصة',
      'pair': 'زوج العملات',
      'create_alert_title': 'إنشاء تنبيه ذكي',
      'frequency': 'فترة الفحص',
      'seconds': 'ثانية',
      'minutes': 'دقيقة',
      'hours': 'ساعة',
    },
    'tr': {
      'my_alerts': 'Alarmlarım',
      'history': 'Geçmiş',
      'settings': 'Ayarlar',
      'smart_alerts_desc': 'Özel zaman çizelgesine göre akıllı izleme',
      'new_alert': 'Yeni Alarm Ekle',
      'last_checked_price': 'Son Kontrol Edilen Fiyat:',
      'check_now': 'Şimdi Kontrol Et',
      'baseline': 'Baz Fiyat',
      'rearm': 'Yeniden Başlat',
      'theme_and_colors': 'Tema ve Renkler',
      'theme_dark_green': 'Koyu Zümrüt (Varsayılan)',
      'theme_light_green': 'Açık Zümrüt',
      'theme_dark_orange': 'Koyu Turuncu',
      'theme_light_orange': 'Açık Turuncu',
      'select_language': 'Dil Seçimi',
      'sound_and_vibrate': 'Ses ve Titreşim',
      'sound_alert': 'Alarm Sesi',
      'vibrate_alert': 'Alarm Titreşimi',
      'test_sound_button': '🔔 Alarm Sesi ve Bildirim Testi',
      'backup_and_restore': 'Yedekleme ve Geri Yükleme',
      'export_backup': 'Alarmları Yedekle (JSON)',
      'restore_backup': 'Geri Yükle',
      'clear_history': 'Bildirim Geçmişini Temizle',
      'battery_settings': 'Pil Optimizasyonu (Android)',
      'battery_active': 'Muaf tutuldu (Sorunsuz çalışır)',
      'battery_request': 'Muafiyet İste',
      'test_alert_title': 'Alarmer Test Bildirimi',
      'test_alert_body': 'Ses ve bildirim cihazınızda başarıyla test edildi!',
      'backup_copied': '✅ Yedek panoya kopyalandı.',
      'restore_success': '🎉 Alarmlar başarıyla geri yüklendi.',
      'exchange': 'Borsa',
      'pair': 'İşlem Çifti',
      'create_alert_title': 'Akıllı Alarm Oluştur',
      'frequency': 'Kontrol Sıklığı',
      'seconds': 'Sn',
      'minutes': 'Dk',
      'hours': 'Saat',
    },
  };

  static String get(String key, String langCode) {
    final dict = _translations[langCode] ?? _translations['fa']!;
    return dict[key] ?? _translations['en']?[key] ?? key;
  }
}
